apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-file
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8080;
        location / {
          return 200 'Hello';
        }
        location /healthz {
          access_log off;
          return 200 'OK';
        }
      }
    }
